const Subjects = [
  {
    id: 1,
    subject_c: "IT101",
    Name: "DataBase Management System",
    Alias: "DBMS",
    Program: "Bachelor of Technology",
    Rec_sta: "A",
    session: "5",
    Elective: "No",
    Credit: 5,
    Th_min_p1: 24,
    Th_min_p2: 18,
    Th_tot: 60,
    Sess_min_p1: 16,
    Sess_min_p2: 12,
    Sess_tot: 40,
    pr_min_p1: 10,
    pr_min_p2: 8,
    pr_tot: 25,
    tw_min_p1: 10,
    tw_min_p2: 8,
    tw_tot: 25,
    tot_min_p: 68,
    Tot_marks: 150,
  },
  {
    id: 2,
    subject_c: "IT101",
    Name: "Advanced Microprocessor System",
    Alias: "DBMS",
    Program: "Bachelor of Technology",
    Rec_sta: "A",
    session: "5",
    Elective: "No",
    Credit: 5,
    Th_min_p1: 24,
    Th_min_p2: 18,
    Th_tot: 60,
    Sess_min_p1: 16,
    Sess_min_p2: 12,
    Sess_tot: 40,
    pr_min_p1: 10,
    pr_min_p2: 8,
    pr_tot: 25,
    tw_min_p1: 10,
    tw_min_p2: 8,
    tw_tot: 25,
    tot_min_p: 68,
    Tot_marks: 150,
  },
  {
    id: 3,
    subject_c: "IT101",
    Name: "Core Java Technology",
    Alias: "DBMS",
    Program: "Bachelor of Technology",
    Rec_sta: "A",
    session: "5",
    Elective: "No",
    Credit: 5,
    Th_min_p1: 24,
    Th_min_p2: 18,
    Th_tot: 60,
    Sess_min_p1: 16,
    Sess_min_p2: 12,
    Sess_tot: 40,
    pr_min_p1: 10,
    pr_min_p2: 8,
    pr_tot: 25,
    tw_min_p1: 10,
    tw_min_p2: 8,
    tw_tot: 25,
    tot_min_p: 68,
    Tot_marks: 150,
  },
];

export default Subjects;
